// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxssuhzzmxwtnaodgpoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4c3N1aHp6bXh3dG5hb2RncG9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyNjA1NTksImV4cCI6MjA1MzgzNjU1OX0.Jpv5MxUz69_ZVrm2vMt0sBudwb-NsuBBRUx5U02K1ew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);